import type { Metadata } from 'next'

import './globals.css'
import localFont from 'next/font/local'
import { Inter } from 'next/font/google'

import { Navigation } from '@/components/navigation'
import QueryClientProvider from '@/lib/queryCient'

const inter = Inter({ subsets: ['latin'], variable: '--font-primary' })
const scriptinaPro = localFont({
  src: '../public/fonts/ScriptinaPro.otf',
  variable: '--font-display',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <QueryClientProvider>
        <body
          className={`${inter.variable} ${scriptinaPro.variable} bg-background font-primary `}
        >
          <div className="max-w-7xl relative mx-auto h-full grid grid-cols-[1.7fr_4fr_2fr]">
            <Navigation />
            {children}
            <aside className="border-l border-l-border"></aside>
          </div>
        </body>
      </QueryClientProvider>
    </html>
  )
}
